resources:
- ../../base/web.yaml
- ../../base/api.yaml
- ../../base/worker.yaml
namespace: portal-staging
replicas:
- name: portal-web
  count: 1
- name: portal-api
  count: 1
- name: portal-worker
  count: 1
